as_manager_node:
  ros__parameters:
    scheduler:
      WCET: 5000000  # ns
      period: 10000000  # ns
      deadline: 10000000  # ns
    
    debug:
      safetyFeatures: false
      verboseCallbacks: false
      verboseHalReads: false

    topics:
      asStateTopic: "/as/status"
      gearUpTopic: "/command/ecu"
      brakeTopic: "/command/brake"
      clutchTopic: "/command/clutch"
      steerTopic: "/command/steer"
      ecuStatusTopic: "/status/ecu"
      resStatusTopic: "/status/res"
      maxonMotorsTopic: "/actuator/status"
      missionSelectedTopic: "/mission/selected"
      stopMessageTopic: "/mission/stop"
      orinOnTopic: "/orin/on"

    ebsSupervisor:
      thresholds:
        ebsTankPressureThreshold: 4
        brakePressureOneActuatorThreshold: 10
        brakePressureBothActuatorsThreshold: 20
        brakePressureMaxonMotorsThreshold: 6
        unbrakePressureThreshold: 5
        rpmTsActiveThreshold: 3000
      
      timeouts:
        assertEbsPressureTimeoutMs: 500  # ms
        assertAllBrakesPressureTimeoutMs: 1000  # ms
        assertOneBrakePressureTimeoutMs: 1000  # ms
        assertNoBrakePressureTimeoutMs: 2000  # ms
        assertMaxonBrakePressureTimeoutMs: 1000  # ms
        assertSdcOpenTimeoutMs: 500  # ms
        assertSdcCloseTimeoutMs: 500  # ms
        continousMonitoringTimeoutsMs: 100  # ms

      filtering:
        brakePressureFrontAlpha: 0.9
        brakePressureRearAlpha: 0.9
        rpmAlpha: 0.9
      
      launch:
        maxonBrakePressure: 0.8